SET(CMAKE_ALL_ERRORS_FATAL TRUE)

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/bin)
set(CMAKE_DEBUG_POSTFIX _D)

set(CPACK_PACKAGING_INSTALL_PREFIX "/opt/simple_file_manager")

set(VERSION_MAJOR 1)
set(VERSION_MINOR 0)
if (NOT DEFINED VERSION_PATCH)
    message(STATUS "VERSION_PATCH isn't defined. '1' used")
    set(VERSION_PATCH 1)
endif()

set(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}-${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}")

set(CPACK_GENERATOR "DEB")

set(CPACK_PACKAGE_DESCRIPTION "Simple file manager created via Qt+QML")
set(CPACK_PACKAGE_VERSION_MAJOR "${VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${VERSION_PATCH}")
set(CPACK_PACKAGE_CONTACT "m.vngr@ya.ru")
set(CPACK_PACKAGE_VENDOR "Mike")

SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "Mike")

set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)

if (CPACK_DEB_COMPONENT_INSTALL)
  set(CPACK_DEBIAN_BIN_PACKAGE_CONTROL_EXTRA "${CPACK_DEBIAN_BIN_PACKAGE_CONTROL_EXTRA}")
  set(CPACK_DEBIAN_BIN_PACKAGE_DEPENDS "debconf")
else ()
  set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA}")
  set(CPACK_DEBIAN_PACKAGE_DEPENDS "debconf")
endif ()

include (CPack)
